spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
# spring retry
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2






## to connect to cloud rabbit mq
#
#spring:
#  rabbitmq:
#    addresses: beaver.rmq.cloudamqp.com
#    username: uxmxgntv
#    password: B3JpS3pRKbKUcXkV8-ZmzD9XN0i_OKJk
#    virtual-host: uxmxgntv
#    listener:
#      simple:
#        acknowledge-mode: manual